# Site settings
title: "Ryan Arman Najafi"
email: "ryanarman@example.com"
description: "Software developer specializing in creating innovative solutions. Explore my projects and blog!"
baseurl: "" # Leave empty for GitHub Pages
url: "https://ryanarman.github.io" # Update if using a custom domain

# Social Media
twitter_username: ryanarman
github_username: ryan-najafi
linkedin_username: ryanarman

# Navigation Links
nav_links:
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Blog"
    url: "/blog/"
  - title: "Contact"
    url: "/contact/"

# Plugins
# theme: minimal-mistakes-jekyll
theme: jekyll-theme-chirpy
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Theme configuration
minima:
  skin: dark # Use the dark skin for a modern look
  social_links: true